# Generated by Django 4.2.21 on 2025-05-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0002_rename_certificatntaionalite_inscription_certificatnationalite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='concoursSouhaiter',
            field=models.CharField(choices=[('licence_twin', ' TWIN'), ('licence_srit', 'SRIT'), ('master_informatique', 'MASTER INFORMATIQUE')], max_length=150),
        ),
    ]
